<?php

namespace frontend\models;

use Yii;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\helpers\VarDumper;

/**
 * This is the model class for table "company".
 *
 * @property integer $id
 * @property string $name
 * @property integer $location_id
 * @property string $email
 * @property string $phone
 * @property string $image_src
 * @property integer $type
 * @property string $description
 *
 * @property BookCompanyProject[] $bookCompanyProjects
 * @property BookUserCompany[] $bookUserCompanies
 */
class Community extends ActiveRecord
{

    public static $limit = 12;
    public static $default_avatar = '@web/img/layer_images/company-avatar.png';
    public $image;

    private static $avatar_path = '@web/img/community/';

    const COMMUNITY_ADMIN_TYPE = 1;
    const COMMUNITY_PARTICIPANT_TYPE = 2;

    const COMMUNITY_TYPE_COMPANY = 1;
    const COMMUNITY_TYPE_TEAM = 2;
    const COMMUNITY_TYPE_PUBLIC_PAGE = 3;
    const COMMUNITY_TYPE_ANOTHER = 4;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'community';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'type'], 'required'],
            [['location_id', 'type'], 'integer'],
            [['description'], 'string'],
            [['name', 'email'], 'string', 'max' => 126],
            [['phone', 'image'], 'string', 'max' => 65],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'location_id' => 'Location ID',
            'email' => 'Email',
            'phone' => 'Phone',
            'image' => 'Image',
            'type' => 'Type',
            'description' => 'Description',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBookCompanyProjects()
    {
        return $this->hasMany(BookCompanyProject::className(), ['company_id' => 'id']);
    }

    public function getParticipants()
    {
        return $this->hasMany(BookUserCompany::className(), ['company_id' => 'id']);
    }

    public function getAdmins()
    {
        return $this->hasMany(BookAdminsCommunity::className(), ['community_id' => 'id']);
    }

    public function getAdminsOfCommunity()
    {
        return $this->hasMany(Person::className(), ['id' => 'admin_id'])
            ->via('admins');
    }

    public function getParticipantsOfCommunity()
    {
        return $this->hasMany(Person::className(), ['id' => 'user_id'])
            ->via('participants');
    }

    public function getPersonsData($type, $page = 1)
    {

        switch ($type) {
            case self::COMMUNITY_ADMIN_TYPE:
                $query = $this->getAdminsOfCommunity();
                break;
            case self::COMMUNITY_PARTICIPANT_TYPE:
                $query = $this->getParticipantsOfCommunity();
                break;
            default:
                return false;
        }

        return Pagination::getData($query, $page, 6, $type);
    }

    public function isPerson($type, $dataArray = [])
    {
        if (empty($dataArray)) {
            switch ($type) {
                case Community::COMMUNITY_ADMIN_TYPE:
                    $dataArray = $this->admins;
                    break;
                case Community::COMMUNITY_PARTICIPANT_TYPE:
                    $dataArray = $this->participants;
                    break;
                default:
                    return null;
            }
        }

        $ids = ArrayHelper::getColumn($dataArray, function ($element) {
            return $element->id;
        });

        $personId = Yii::$app->user->id;
        return in_array($personId, $ids);
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub

        $this->setImage();

    }

    private function setImage()
    {

        $image = $this->image_src;
        $path = Yii::getAlias('@frontend') . '/web' . self::$avatar_path;
        $isImageExist = file_exists($path . $image);
        if ($image && $isImageExist) {
            $this->image = Yii::getAlias('@web') . self::$avatar_path . $image;
        } else {
            $this->image = static::$default_avatar;
        }

    }

}
