<?php

namespace frontend\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "company".
 *
 * @property integer $id
 * @property string $name
 * @property integer $location_id
 * @property string $email
 * @property string $phone
 * @property string $image
 *
 * @property BookCompanyProject[] $bookCompanyProjects
 * @property BookUserCompany[] $bookUserCompanies
 */
class Company extends ActiveRecord
{

    public static $limit = 1;

    private static $avatar_path = '@web/img/avatars/company/';

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'company';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['location_id'], 'integer'],
            [['name', 'email'], 'string', 'max' => 126],
            [['phone', 'image'], 'string', 'max' => 65],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'location_id' => 'Location ID',
            'email' => 'Email',
            'phone' => 'Phone',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBookCompanyProjects()
    {
        return $this->hasMany(BookCompanyProject::className(), ['company_id' => 'id']);
    }

    public function getUsersForCompanies()
    {
        return $this->hasMany(BookUserCompany::className(), ['company_id' => 'id']);
    }

    public function getPersons()
    {
        return $this->hasMany(Person::className(), ['id' => 'user_id'])
            ->via('usersForCompanies');
    }

    public function getPersonsData($page = 1)
    {
        $query = $this->getPersons();
        return Pagination::getData($query, $page, Person::$limit, 'persons');
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub

        $image = $this->image;
        if ($image) {
            $this->image = self::$avatar_path . $image;
        } else {
            $this->image = '@web/img/layer_images/company-avatar.png';
        }

    }

}
